// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {document} from '../models';
import {domain} from '../models';
import {exporter} from '../models';
import {generator} from '../models';
import {judge} from '../models';

export function BuildDocument(arg1:document.Request):Promise<document.Result>;

export function CompareOutput(arg1:domain.CheckerConfig,arg2:string,arg3:string):Promise<boolean>;

export function CreateProblem(arg1:string,arg2:domain.ProblemConfig):Promise<domain.ProblemSummary>;

export function CreateProject(arg1:string):Promise<domain.Project>;

export function ExportProject(arg1:exporter.Request):Promise<void>;

export function GenerateTests(arg1:generator.Request):Promise<generator.Result>;

export function GetProblem(arg1:string,arg2:string):Promise<domain.ProblemSummary>;

export function GetRecentProjects():Promise<Array<domain.Project>>;

export function OpenProjectDialog():Promise<domain.Project>;

export function OpenRecentProject(arg1:string):Promise<domain.Project>;

export function RunCommand(arg1:judge.Request):Promise<judge.Result>;

export function SaveProblemConfig(arg1:string,arg2:string,arg3:domain.ProblemConfig):Promise<void>;
