// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareOutput(arg1, arg2, arg3) {
  return window['go']['app']['App']['CompareOutput'](arg1, arg2, arg3);
}

export function CreateProblem(arg1, arg2) {
  return window['go']['app']['App']['CreateProblem'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['app']['App']['CreateProject'](arg1);
}

export function ExportProject(arg1) {
  return window['go']['app']['App']['ExportProject'](arg1);
}

export function GenerateTests(arg1) {
  return window['go']['app']['App']['GenerateTests'](arg1);
}

export function GetProblem(arg1, arg2) {
  return window['go']['app']['App']['GetProblem'](arg1, arg2);
}

export function GetRecentProjects() {
  return window['go']['app']['App']['GetRecentProjects']();
}

export function OpenProjectDialog() {
  return window['go']['app']['App']['OpenProjectDialog']();
}

export function OpenRecentProject(arg1) {
  return window['go']['app']['App']['OpenRecentProject'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['app']['App']['RunCommand'](arg1);
}

export function SaveProblemConfig(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveProblemConfig'](arg1, arg2, arg3);
}
