// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function OpenRecentProject(arg1) {
  return window['go']['main']['App']['OpenRecentProject'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
